import { initNavToggle } from './nav-toggle';
import { initNavDropdowns } from './nav-dropdown';
import { initDialogs } from './dialog';
import { initPopovers } from './popover';
import { initVideoFacades } from './video-facade';
import { initLenis } from './lenis-init';
import { initPrimaryHero } from './primary-hero';
import { initSecondaryHero } from './secondary-hero';
import { initCardsSections } from './cards-section';
import { initThreePoints } from './three-points';
import { initTimelines } from './timeline';
import { initShareButtons } from './share';
import { initRelatedInsights } from './related-insights';
import { initHoldings } from './holdings';
import { initGeoCharts } from './geo-chart';
import { initDocumentLibraries } from './document-library';

document.addEventListener('DOMContentLoaded', () => {
	initLenis();
	initNavToggle();
	initNavDropdowns();
	initDialogs();
	initPopovers();
	initVideoFacades();
	initPrimaryHero();
	initSecondaryHero();
	initCardsSections();
	initThreePoints();
	initTimelines();
	initShareButtons();
	initRelatedInsights();
	initHoldings();
	initGeoCharts();
	initDocumentLibraries();
});
